"""
""" Try to load minpac
"""

packadd minpac
if !exists('*minpac#init')
  " In case if minpac is not available init with settings for plugin-less environment:
  " ...
else
  " In case if minpac is available init with verbosity 3 (to see minpac work):
  call minpac#init({'verbose': 3})
  " List of additional packs minpac could install:
  call minpac#add('k-takata/minpac', {'type': 'opt'})
  call minpac#add('airblade/vim-gitgutter')
  call minpac#add('altercation/vim-colors-solarized')
  call minpac#add('itchyny/lightline.vim')
  call minpac#add('prettier/vim-prettier')
  call minpac#add('tpope/vim-commentary')
  call minpac#add('tpope/vim-endwise')
  call minpac#add('tpope/vim-fugitive')
  call minpac#add('tpope/vim-repeat')
  call minpac#add('tpope/vim-surround')
  " Minpac utility commands (run manually):
  command! PackUpdate call minpac#update()
  command! PackClean call minpac#clean()
  command! PackStatus call minpac#status()
  " Plugin settings here:
  " ...
endif

"""
""" Init all common (packet agnostic) nvim settings
"""

" turn filetype detection, indent scripts and filetype plugins on
filetype plugin indent on
" and syntax highlighting too
syntax on

" leader
let mapleader=","
" no timeout for leader (wait forever for mapped key after pressing leader)
set notimeout

set clipboard^=unnamed,unnamedplus " merge with system clopboard

set hlsearch		" highlight search results
set nocompatible	" disable vi-compatibility
set showmode		" always show what mode we're currently editing in
set list		" show whitespaces
set number		" show line numbers
set mouse=a		" enable mouse
set showcmd		" show <leader> pressed
set cursorline		" highlight current line
set wildmenu		" show mathch files as menu when use TAB
set lazyredraw		" redraw only when we need to

set ignorecase		" ignore case when searching
set smartcase		" ignore case if search pattern is all lowercase

"""""
""""" Mappings
"""""
" begingin of line
nnoremap H 0
" end of line
nnoremap L $
" begingin of file
nnoremap J G
" ending of file
nnoremap K gg

" left tab
nnoremap <C-Left> :tabprevious<CR>
" right tab
nnoremap <C-Right> :tabnext<CR>
" move tab left
nnoremap <silent> <A-Left> :execute 'silent! tabmove ' . (tabpagenr()-2)<CR>
" move tab right
nnoremap <silent> <A-Right> :execute 'silent! tabmove ' . (tabpagenr()+1)<CR>
" Show all buffers in tabs, or to close all tabs (toggle: it alternately executes  :tab ball and :tabo).
let notabs = 0
nnoremap <silent> <F8> :let notabs=!notabs<Bar>:if notabs<Bar>:tabo<Bar>:else<Bar>:tab ball<Bar>:tabn<Bar>:endif<CR>

" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %

"set showmatch		" highlight matching [{()}]	ALREADY WORKS VIA vim-sensitive
"nnoremap j gj		" move vertically by visual line	
"nnoremap k gk		" ALREADY WORKS VIA vim-sensitive

" map select all to CTRL-a
map <C-a> <esc>ggVG<CR>

" format json
map <leader>pj :%!python -m json.tool<CR>
" format xml
map <leader>px :%!xmllint % --format<CR>-
